# Generated by Django 5.1.7 on 2025-05-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitnesscenter', '0001_initial'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='mentors.mentorprofile'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='fitnesscenter.organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='fitnesscenter.organization'),
        ),
        migrations.AddField(
            model_name='organizationamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='fitnesscenter.amenity'),
        ),
        migrations.AddField(
            model_name='organizationamenity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='fitnesscenter.organization'),
        ),
        migrations.AddField(
            model_name='organizationphoto',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fitnesscenter.organization'),
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fitnesscenter.organization'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='fitnesscenter.organization'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='fitnesscenter.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationamenity',
            unique_together={('organization', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='socialmedia',
            unique_together={('organization', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together={('organization', 'day')},
        ),
    ]
