# Generated by Django 5.1.7 on 2025-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
