# Generated by Django 5.1.7 on 2025-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0003_alter_socialmedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='anniversary_wish_message',
            field=models.TextField(blank=True, help_text='Default anniversary message to show to users', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='birthday_wish_message',
            field=models.TextField(blank=True, help_text='Default birthday message to show to users', null=True),
        ),
    ]
