# Generated by Django 5.1.7 on 2025-05-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0004_organization_anniversary_wish_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
