# Generated by Django 5.1.7 on 2025-06-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0005_alter_socialmedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_slot_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
