# Generated by Django 5.1.7 on 2025-08-25 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0006_organization_average_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmiPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_name', models.CharField(max_length=100)),
                ('number_of_installments', models.PositiveIntegerField()),
                ('emi_amount_per_cycle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_plans', to='fitnesscenter.membershipplan')),
            ],
        ),
    ]
