# Generated by Django 5.1.7 on 2025-09-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0007_emiplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
