# Generated by Django 5.1.7 on 2025-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0009_bankaccountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_completeness',
            field=models.PositiveIntegerField(default=0, help_text='Profile completeness percentage'),
        ),
    ]
