# Generated by Django 5.1.7 on 2025-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0010_organization_profile_completeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='razorpay_account_status',
            field=models.CharField(choices=[('Verification_Failed', 'Verification_Failed'), ('Activated', 'Activated'), ('Not_Activated', 'Not_Activated'), ('Verification_Pending', 'Verification_Pending')], default='Not_Activated', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='razorpay_error_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='razorpay_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
