# Generated by Django 5.1.7 on 2026-01-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0012_remove_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('pvt_ltd', 'Private Limited'), ('limited', 'Limited'), ('not_yet_registered', 'Not Yet Registered')], default='individual', help_text='Business type for Razorpay linked account', max_length=50, null=True),
        ),
    ]
