# Generated by Django 5.1.7 on 2026-03-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0014_add_pan_and_dob_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('pvt_ltd', 'Private Limited'), ('limited', 'Limited'), ('not_yet_registered', 'Not Yet Registered')], default='individual', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='razorpay_account_status',
            field=models.CharField(choices=[('Verification_Failed', 'Verification Failed'), ('Activated', 'Activated'), ('Not_Activated', 'Not Activated'), ('Verification_Pending', 'Verification Pending')], default='Not_Activated', max_length=25),
        ),
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='razorpay_error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
