# Generated by Django 5.2.11 on 2026-04-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0015_alter_bankaccountdetails_business_type_and_more'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='mentors.mentorprofile'),
        ),
    ]
