# Generated by Django 5.1.7 on 2026-04-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0016_make_mentor_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Morning, Evening, Special Batch', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='fitnesscenter.organization')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
