# Generated by Django 5.1.7 on 2026-05-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0018_organization_registration_status'),
        ('trainer', '0022_workoutplan_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationtimeslot',
            options={},
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Direct link to banner image if no file is uploaded', max_length=500, null=True)),
                ('banner_type', models.CharField(choices=[('promotional', 'Promotional'), ('workout_log', 'Workout Log Page'), ('global', 'Global/System')], default='promotional', max_length=20)),
                ('target_screen', models.CharField(blank=True, help_text='Optional target screen identifier for deep linking', max_length=100, null=True)),
                ('external_link', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotional_banners', to='fitnesscenter.organization')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotional_banners', to='trainer.trainer')),
            ],
        ),
    ]
