# Generated by Django 5.1.7 on 2026-06-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0019_alter_organizationtimeslot_options_promotionalbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtimeslot',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional end date when this slot ceases to be active', null=True),
        ),
        migrations.AddField(
            model_name='organizationtimeslot',
            name='start_date',
            field=models.DateField(blank=True, help_text='Optional start date when this slot becomes active', null=True),
        ),
    ]
