# Generated by Django on 2026-06-05

from django.db import migrations

def update_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get model classes
    Organization = apps.get_model('fitnesscenter', 'Organization')
    Location = apps.get_model('fitnesscenter', 'Location')
    WorkingDay = apps.get_model('fitnesscenter', 'WorkingDay')
    OrganizationPhoto = apps.get_model('fitnesscenter', 'OrganizationPhoto')
    SocialMedia = apps.get_model('fitnesscenter', 'SocialMedia')
    OrganizationTimeSlot = apps.get_model('fitnesscenter', 'OrganizationTimeSlot')
    organizationAmenity = apps.get_model('fitnesscenter', 'organizationAmenity')
    
    group_name = 'Organization Editor'
    group, _ = Group.objects.get_or_create(name=group_name)

    editable_models = [
        Organization,
        Location,
        WorkingDay,
        OrganizationPhoto,
        SocialMedia,
        OrganizationTimeSlot,
        organizationAmenity,
    ]

    perms = []
    for model in editable_models:
        ct = ContentType.objects.get_for_model(model)
        for prefix in ['view', 'change', 'add', 'delete']:
            codename = f'{prefix}_{model._meta.model_name}'
            perm = Permission.objects.filter(content_type=ct, codename=codename).first()
            if perm:
                perms.append(perm)

    group.permissions.set(perms)
    group.save()

def reverse_group_permissions(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0020_organizationtimeslot_end_date_and_more'),
    ]

    operations = [
        migrations.RunPython(update_group_permissions, reverse_code=reverse_group_permissions),
    ]
