# Generated by Django 5.1.7 on 2026-06-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0021_update_organization_editor_permissions'),
        ('trainer', '0023_workoutsession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_functional', models.BooleanField(default=True, help_text='Set to False if the equipment is temporarily out of order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_equipments', to='fitnesscenter.organization')),
            ],
            options={
                'verbose_name_plural': 'Gym Equipment Inventory',
                'unique_together': {('organization', 'equipment')},
            },
        ),
    ]
