# Generated by Django 5.1.7 on 2026-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0022_gymequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
