# Generated by Django 5.1.7 on 2026-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0023_location_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingday',
            name='ladies_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingday',
            name='ladies_opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
