# Generated by Django 5.1.7 on 2025-05-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitnesscenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('admin', 'admin'), ('accounts', 'accounts'), ('trainer', 'trainer')], default='admin', max_length=10)),
                ('hash_of_user_phone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('experience', models.CharField(blank=True, help_text='Years of experience', max_length=50, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True)),
                ('address_proof', models.FileField(blank=True, help_text='Upload address proof', null=True, upload_to='documents/address_proofs/')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories the mentor belongs to', related_name='mentors', to='fitnesscenter.category')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization the mentor belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='fitnesscenter.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, help_text='Upload fitness certificate', null=True, upload_to='documents/trainer_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the certificate was uploaded')),
                ('mentor_profile', models.ForeignKey(help_text='Mentor profile associated with this fitness certificate', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_certificates', to='mentors.mentorprofile')),
            ],
            options={
                'verbose_name': 'Fitness Certificate',
                'verbose_name_plural': 'Fitness Certificates',
            },
        ),
    ]
