# Generated by Django 5.1.7 on 2025-06-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Body Mass Index (auto-calculated)', max_digits=5, null=True),
        ),
    ]
