# Generated by Django 5.1.7 on 2025-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bf_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Body Fat Percentage (auto-calculated)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bmr',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Basal Metabolic Rate (auto-calculated)', max_digits=6, null=True),
        ),
    ]
