# Generated by Django 5.1.7 on 2025-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_injury_medicalcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Just starting out'), ('Intermediate', 'Working out regularly'), ('Advanced', 'Training intensely')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='injuries',
            field=models.ManyToManyField(blank=True, related_name='customers', to='customers.injury'),
        ),
        migrations.AddField(
            model_name='customer',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, related_name='customers', to='customers.medicalcondition'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sleep_goal',
            field=models.CharField(blank=True, choices=[('5-6 hours', '5 - 6 Hours'), ('6-7 hours', '6 - 7 Hours'), ('7-8 hours', '7 - 8 Hours'), ('8-9 hours', '8 - 9 Hours'), ('Above 9 hours', 'Above 9 Hours')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='stress_level',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('High', 'High'), ('Severe', 'Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target Weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_goal',
            field=models.CharField(blank=True, choices=[('Lose', 'Lose'), ('Gain', 'Gain'), ('Maintain', 'Maintain')], max_length=20, null=True),
        ),
    ]
