# Generated by Django 5.1.7 on 2025-06-27 12:03

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_fitness_level_customer_injuries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='user',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerreview',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
