# Generated by Django 5.1.7 on 2025-06-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_customerreview_created_at_and_more'),
        ('fitnesscenter', '0006_organization_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerreview',
            unique_together={('organization', 'customer')},
        ),
    ]
