# Generated by Django 5.1.7 on 2025-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customermembership_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembership',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermembership',
            name='next_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
