# Generated by Django 5.1.7 on 2025-08-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customermembership_last_payment_date_and_more'),
        ('fitnesscenter', '0007_emiplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembership',
            name='emi_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitnesscenter.emiplan'),
        ),
    ]
