# Generated by Django 5.1.7 on 2025-10-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customermembership_emi_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='average_sleep_hours',
            field=models.CharField(blank=True, choices=[('4-5_hours', '4 - 5 Hours'), ('5-6_hours', '5 - 6 Hours'), ('6-7_hours', '6 - 7 Hours'), ('7-8_hours', '7 - 8 Hours'), ('8-9_hours', '8 - 9 Hours'), ('Above_9_hours', 'Above 9 Hours')], help_text='Average daily sleep hours', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='average_working_hours',
            field=models.CharField(blank=True, choices=[('<4_hours', '< 4 Hours'), ('4-6_hours', '4 - 6 Hours'), ('6-8_hours', '6 - 8 Hours'), ('8-10_hours', '8 - 10 Hours'), ('10+_hours', '10+ Hours')], help_text='Average daily working hours', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_satisfaction',
            field=models.IntegerField(blank=True, choices=[(5, 'Very Happy'), (4, 'Happy'), (3, 'Neutral'), (2, 'Unhappy'), (1, 'Very Unhappy')], help_text='How happy are you with your current profession?', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='other_profession',
            field=models.CharField(blank=True, help_text="Specify if profession is 'Other'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_completeness',
            field=models.PositiveIntegerField(default=0, help_text='Profile completeness percentage'),
        ),
        migrations.AddField(
            model_name='customer',
            name='target_goal',
            field=models.CharField(blank=True, choices=[('Build_Muscle', 'Build Muscle'), ('Loss_Weight', 'Loss Weight'), ('Gain_Weight', 'Gain Weight'), ('Stay_Consistent', 'Stay Consistent'), ('Improve_Stamina', 'Improve Stamina'), ('Improve_Endurance', 'Improve Endurance'), ('Increase_Flexibility', 'Increase Flexibility'), ('General_Fitness', 'General Fitness'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='target_goal_other',
            field=models.CharField(blank=True, help_text="Specify if target goal is 'Other'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profession',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Software_Engineer', 'Software Engineer'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Teacher', 'Teacher'), ('Business_Owner', 'Business Owner'), ('Freelancer', 'Freelancer'), ('Home_Maker', 'Home Maker'), ('Government_Employee', 'Government Employee'), ('Corporate_Employee', 'Corporate Employee'), ('Armed_Forces', 'Armed Forces'), ('Athlete', 'Athlete'), ('Trainer', 'Trainer'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sleep_goal',
            field=models.CharField(blank=True, choices=[('4-5_hours', '4 - 5 Hours'), ('5-6_hours', '5 - 6 Hours'), ('6-7_hours', '6 - 7 Hours'), ('7-8_hours', '7 - 8 Hours'), ('8-9_hours', '8 - 9 Hours'), ('Above_9_hours', 'Above 9 Hours')], max_length=20, null=True),
        ),
    ]
