# Generated by Django 5.1.7 on 2025-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_average_sleep_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_scale',
            field=models.PositiveIntegerField(blank=True, help_text='Active Scale score', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='health_conditions',
            field=models.CharField(blank=True, choices=[('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Heart_Disease', 'Heart Disease'), ('Asthma', 'Asthma'), ('Obesity', 'Obesity'), ('Arthritis', 'Arthritis'), ('Depression', 'Depression'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='health_conditions_other',
            field=models.CharField(blank=True, help_text="Specify if health condition is 'Other'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_healthy',
            field=models.BooleanField(default=True, help_text='True if the customer is healthy, False if they have health conditions.'),
        ),
    ]
