# Generated by Django 5.1.7 on 2025-11-04 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_active_scale_customer_health_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='health_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Diabetes', 'Diabetes'), ('Hypertension', 'Hypertension'), ('Heart_Disease', 'Heart Disease'), ('Asthma', 'Asthma'), ('Obesity', 'Obesity'), ('Arthritis', 'Arthritis'), ('Depression', 'Depression'), ('Other', 'Other')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
