# Generated by Django 5.1.7 on 2025-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customer_health_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembership',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
