# Generated by Django 5.1.7 on 2025-11-19 08:23

import django.contrib.postgres.fields
from django.db import migrations, models


def convert_target_goal(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    for c in Customer.objects.all():
        if isinstance(c.target_goal, str):
            c.target_goal = [c.target_goal]
            c.save(update_fields=["target_goal"])
class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customermembership_razorpay_subscription_id'),
    ]

    operations = [
        migrations.RunPython(convert_target_goal),
        migrations.AlterField(
            model_name='customer',
            name='target_goal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Build_Muscle', 'Build Muscle'), ('Loss_Weight', 'Loss Weight'), ('Gain_Weight', 'Gain Weight'), ('Stay_Consistent', 'Stay Consistent'), ('Improve_Stamina', 'Improve Stamina'), ('Improve_Endurance', 'Improve Endurance'), ('Increase_Flexibility', 'Increase Flexibility'), ('General_Fitness', 'General Fitness'), ('Other', 'Other')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
