# Generated by Django 5.1.7 on 2026-01-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_target_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='status',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Hold', 'Hold')], default='PENDING', max_length=20),
        ),
    ]
