# Generated by Django 5.1.7 on 2026-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_add_hold_status_to_customermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembershiptransaction',
            name='transfer_status',
            field=models.CharField(choices=[('not_initiated', 'Not Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='not_initiated', help_text='Status of payment transfer to gym account', max_length=20),
        ),
    ]
