# Generated by Django 5.1.7 on 2026-03-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_add_transfer_status_to_transaction'),
        ('fitnesscenter', '0015_alter_bankaccountdetails_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Customer notes/remarks', null=True)),
                ('gym_remarks', models.TextField(blank=True, help_text='Gym remarks on acceptance/rejection', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='customers.customer')),
                ('membership_plan', models.ForeignKey(blank=True, help_text='Plan selected by the customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requests', to='fitnesscenter.membershipplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='fitnesscenter.organization')),
                ('selected_plan', models.ForeignKey(blank=True, help_text='Plan selected/assigned by the gym', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_assigned_requests', to='fitnesscenter.membershipplan')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
