# Generated by Django 5.1.7 on 2026-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_membershiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='accepted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount set by gym', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount given by gym', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Membership end date set by gym', null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Membership start date set by gym', null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='transaction_number',
            field=models.CharField(blank=True, help_text='Cash/offline transaction reference number', max_length=100, null=True),
        ),
    ]
