# Generated by Django 5.1.7 on 2026-05-26 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_membershiprequest_accepted_amount_and_more'),
        ('trainer', '0021_alter_customerworkoutplan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='contact_info',
            field=models.JSONField(blank=True, help_text='Gym contact details when proposing a plan', null=True),
        ),
        migrations.AlterField(
            model_name='customermembership',
            name='status',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Hold', 'Hold')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('contacted', 'Contacted')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='customers.customer')),
                ('membership_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.membershiprequest')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.workoutplan')),
            ],
        ),
    ]
