# Generated by Django 5.1.7 on 2026-05-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_membershiprequest_contact_info_and_more'),
        ('user', '0006_subscriptiontransaction_membership_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembershiptransaction',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_transactions', to='user.coupon'),
        ),
    ]
