# Generated by Django 5.1.7 on 2026-06-23 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_customermembershiptransaction_coupon'),
        ('trainer', '0024_workoutplan_is_preset_alter_workoutsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='trainer.trainer'),
        ),
    ]
