# Generated by Django 5.1.7 on 2026-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_customer_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trainer_notes',
            field=models.TextField(blank=True, help_text='Notes/remarks added by the trainer', null=True),
        ),
    ]
