# Generated by Django 5.1.7 on 2026-06-30 08:35

import datetime
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_customer_trainer_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('coin_reward', models.PositiveIntegerField(default=10)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField(help_text='Calories per serving')),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('serving_size', models.CharField(default='100g', max_length=100)),
                ('is_global', models.BooleanField(default=True)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BodyMeasurementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biceps_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thighs_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('logged_at', models.DateField(default=datetime.date.today)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_logs', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('custom', 'Custom Post'), ('workout_completed', 'Workout Completed'), ('pr_achieved', 'Personal Record Achieved'), ('streak_milestone', 'Streak Milestone')], default='custom', max_length=25)),
                ('caption', models.TextField(blank=True, null=True)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='customers.communitypost')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snacks')], max_length=20)),
                ('servings', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('logged_at', models.DateField(default=datetime.date.today)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='customers.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.food')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='progress_photos/')),
                ('photo_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], max_length=10)),
                ('logged_at', models.DateField(default=datetime.date.today)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.PositiveIntegerField(help_text='Amount in ml')),
                ('logged_at', models.DateField(default=datetime.date.today)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('logged_at', models.DateField(default=datetime.date.today)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='customers.communitypost')),
            ],
            options={
                'unique_together': {('post', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.badge')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='customers.customer')),
            ],
            options={
                'unique_together': {('customer', 'badge')},
            },
        ),
    ]
