# Generated by Django 5.1.7 on 2026-07-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_badge_food_bodymeasurementlog_communitypost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trainer_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the trainer was assigned', null=True),
        ),
    ]
