# Generated by Django 5.1.7 on 2026-05-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_membershiprequest_contact_info_and_more'),
        ('trainer', '0021_alter_customerworkoutplan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_workout_plans', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customerworkoutplan',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workout_plans', to='trainer.trainer'),
        ),
    ]
