# Generated by Django 5.1.7 on 2026-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0022_workoutplan_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
