# Generated by Django 5.1.7 on 2026-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0023_workoutsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_preset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('rest_day', 'Rest Day')], default='pending', max_length=20),
        ),
    ]
