# Generated by Django 5.1.7 on 2026-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0024_workoutplan_is_preset_alter_workoutsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesetlog',
            name='previous_reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
