# Generated by Django 5.1.7 on 2026-06-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0025_exercisesetlog_previous_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerworkoutplan',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
