# Generated by Django 5.1.7 on 2026-06-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0026_customerworkoutplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesettemplate',
            name='input_type',
            field=models.CharField(choices=[('reps', 'Reps'), ('seconds', 'Seconds'), ('minutes', 'Minutes'), ('distance', 'Distance'), ('calories', 'Calories'), ('custom', 'Custom')], default='reps', max_length=20),
        ),
        migrations.AddField(
            model_name='exercisesetlog',
            name='input_type',
            field=models.CharField(default='reps', max_length=20),
        ),
        migrations.AddField(
            model_name='exercisesetlog',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
