# Generated by Django 5.1.7 on 2026-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0027_exercisesettemplate_input_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='track_by',
            field=models.CharField(blank=True, choices=[('rep', 'Reps'), ('time', 'Time'), ('distance', 'Distance')], default='rep', max_length=20, null=True),
        ),
    ]
