# Generated by Django 5.1.7 on 2026-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0028_workout_track_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='weight_type',
            field=models.CharField(blank=True, default='kg', max_length=20, null=True),
        ),
    ]
