"""
Django settings for discipl project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from dotenv import load_dotenv
import os
if os.name == 'nt':
    try:
        os.add_dll_directory(r"C:\OSGeo4W\bin")
    except Exception:
        pass

GDAL_LIBRARY_PATH = r"C:\OSGeo4W\bin\gdal312.dll" if os.name == 'nt' else None
GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll" if os.name == 'nt' else None
from .config.base import ( # noqaL F401,F403
    BASE_DIR,
    to_bool,
    to_list
)
load_dotenv()

from pathlib import Path



SECRET_KEY = 'django-insecure-@$p8xyj(62u(3386omey02jo@nqgn+0me4w8wau6b(3tv5=*w4'

DEBUG = to_bool('DEBUG')
ALLOWED_HOSTS = [
    host.strip() 
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',') 
    if host.strip()
]

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",
    "drf_spectacular",
    'storages',
    'rest_framework',
    
    # apps
    'apps.user',
    'apps.communication',
    'apps.customers',
    'apps.fitnesscenter',
    'apps.mentors',
    'apps.subscription',
    'apps.trainer',
    'import_export'
]


# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
#     # custom middleware
#     'apps.utils.middlewares.headers.HeadersMiddleWare',
#     'apps.utils.middlewares.csrf.CsrfExemptMiddleware',
#     'apps.utils.middlewares.exception.CustomExceptionMiddleware',
#     'apps.utils.middlewares.mentor.MentorMiddleware',
# ]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'apps.utils.middlewares.headers.HeadersMiddleWare',
    'apps.utils.middlewares.csrf.CsrfExemptMiddleware',

    # disable for debugging
    # 'apps.utils.middlewares.exception.CustomExceptionMiddleware',

    'apps.utils.middlewares.exception.CustomExceptionMiddleware',
    'apps.utils.middlewares.mentor.MentorMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-Platform',
]

WSGI_APPLICATION = 'discipl.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'user.User'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'public/static')
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_OTP = 2222
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET')
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

# Razorpay Transfer Configuration
MIN_PLATFORM_FEE = float(os.getenv('MIN_PLATFORM_FEE', '4.00'))  # Minimum platform fee in rupees

# Database configuration is handled by discipl/config/db.py using env vars
from discipl.config.base import *
from discipl.config.db import *
from discipl.config.route import *
from discipl.config.templates import *
from discipl.config.auth import *
from discipl.config.drf import *
from discipl.config.apps import *
from discipl.config.payment import *
from discipl.config.sms import *
