# Generated by Django 5.1.7 on 2026-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_coupon_and_commission_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='share_value',
            field=models.DecimalField(decimal_places=2, help_text='Executive commission percentage or fixed amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='otpstore',
            name='source',
            field=models.CharField(blank=True, choices=[('mentor-app-ios', 'Mentor App IOS'), ('mentor-app-web', 'Mentor App Web'), ('mentor-app-android', 'Mentor App Android'), ('customer-app-ios', 'Customer App IOS'), ('customer-app-android', 'Customer App Android'), ('admin-web', 'Admin Web'), ('vendor-app-android', 'Vendor APP Android'), ('vendor-app-ios', 'Vendor APP IOS')], max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='platform',
            field=models.CharField(blank=True, choices=[('mentor-app-ios', 'Mentor App IOS'), ('mentor-app-web', 'Mentor App Web'), ('mentor-app-android', 'Mentor App Android'), ('customer-app-ios', 'Customer App IOS'), ('customer-app-android', 'Customer App Android'), ('admin-web', 'Admin Web'), ('vendor-app-android', 'Vendor APP Android'), ('vendor-app-ios', 'Vendor APP IOS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Discipl Admin'), (10, 'Discipl Accountant'), (15, 'Discipl Agent'), (20, 'Mentor'), (25, 'Mentor Staff'), (30, 'Mentor Accounts'), (35, 'Mentor Trainer'), (36, 'Mentor Dietitian'), (45, 'Customer'), (40, 'Vendor')], db_index=True, default=100),
        ),
    ]
