# Generated by Django 5.1.7 on 2026-05-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0019_alter_organizationtimeslot_options_promotionalbanner'),
        ('user', '0004_alter_coupon_share_value_alter_otpstore_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='fitnesscenter.organization'),
        ),
        migrations.AddField(
            model_name='salesexecutive',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_executives', to='fitnesscenter.organization'),
        ),
    ]
