# Generated by Django 5.1.7 on 2026-05-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesscenter', '0019_alter_organizationtimeslot_options_promotionalbanner'),
        ('subscription', '0008_organizationtransaction_coupon'),
        ('user', '0005_affiliate_org_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitnesscenter.membershipplan'),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.disciplsubscriptionplan'),
        ),
    ]
