# Generated by Django 5.1.7 on 2026-05-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('customers', '0021_membershiprequest_contact_info_and_more'),
        ('fitnesscenter', '0018_organization_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('deduction', 'Deduction'), ('refund', 'Refund')], max_length=20)),
                ('credits', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount for purchases', max_digits=10, null=True)),
                ('reference_type', models.CharField(blank=True, default='', help_text='campaign, automation, manual, purchase', max_length=50)),
                ('reference_id', models.BigIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('payment_id', models.CharField(blank=True, default='', help_text='Razorpay payment ID for purchases', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='fitnesscenter.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.IntegerField(default=0)),
                ('used_credits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to='fitnesscenter.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('rendered_message', models.TextField(blank=True, default='', help_text='Final rendered message text')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Template variables used for rendering')),
                ('scheduled_at', models.DateTimeField(help_text='When to send this message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='automation', help_text='automation, campaign, manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_messages', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_queue', to='fitnesscenter.organization')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, default='', help_text='Message ID from Meta API response', max_length=200)),
                ('response', models.JSONField(blank=True, default=dict, help_text='Full API response')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='communication.messagequeue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday Greeting'), ('expiry_reminder', 'Membership Expiry Reminder'), ('renewal_reminder', 'Renewal Reminder'), ('festival', 'Festival Greeting'), ('welcome', 'Welcome Message'), ('payment_confirmation', 'Payment Confirmation'), ('custom', 'Custom')], max_length=30)),
                ('meta_template_id', models.CharField(blank=True, default='', help_text='Template ID from Meta WhatsApp Business API', max_length=200)),
                ('content', models.TextField(help_text='Message body with {{member_name}}, {{gym_name}}, {{expiry_date}}, {{renewal_amount}} placeholders')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of supported placeholder names')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_approval', 'Pending Approval')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='fitnesscenter.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='messagequeue',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_messages', to='communication.whatsapptemplate'),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('expiry_reminder', 'Membership Expiry Reminder'), ('renewal_reminder', 'Renewal Reminder'), ('onam', 'Onam'), ('vishu', 'Vishu'), ('christmas', 'Christmas'), ('eid', 'Eid'), ('new_year', 'New Year')], max_length=30)),
                ('trigger_days_before', models.IntegerField(default=0, help_text='Days before the event to trigger (0 = on the day)')),
                ('send_time', models.TimeField(default='09:00', help_text='Time of day to send (IST)')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='fitnesscenter.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='communication.whatsapptemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'event_type')},
            },
        ),
    ]
