# Generated by Django 5.1.7 on 2026-01-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_add_hold_status_to_customermembership'),
        ('subscription', '0003_add_hold_status_to_organizationsubscriptionsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertransfer',
            name='customer_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transfers', to='customers.customermembershiptransaction'),
        ),
        migrations.AddConstraint(
            model_name='partnertransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_transaction__isnull', False)), fields=('customer_transaction',), name='uniq_transfer_per_subscription_payment'),
        ),
    ]
