# Generated by Django 5.1.7 on 2026-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_add_transfer_status_to_transaction'),
        ('subscription', '0004_partnertransfer_customer_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partnertransfer',
            name='uniq_transfer_per_subscription_payment',
        ),
        migrations.AddField(
            model_name='partnertransfer',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details for failed attempts', null=True),
        ),
        migrations.AddField(
            model_name='partnertransfer',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last retry', null=True),
        ),
        migrations.AddField(
            model_name='partnertransfer',
            name='notes',
            field=models.TextField(blank=True, help_text='Transfer notes with customer and gym info', null=True),
        ),
        migrations.AddField(
            model_name='partnertransfer',
            name='original_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original payment amount before split', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partnertransfer',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee deducted (in rupees)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partnertransfer',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AddConstraint(
            model_name='partnertransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_transaction__isnull', False), ('status', 'processed')), fields=('customer_transaction', 'status'), name='uniq_successful_transfer_per_payment'),
        ),
    ]
