# Generated by Django 5.1.7 on 2026-01-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_enhance_partner_transfer_for_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertransfer',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('processed', 'Processed'), ('settled', 'Settled'), ('failed', 'Failed')], default='created', help_text='Status of the transfer', max_length=50),
        ),
    ]
