# Generated by Django 5.1.7 on 2026-05-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_organizationtransaction_trainer_fields'),
        ('user', '0005_affiliate_org_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtransaction',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_transactions', to='user.coupon'),
        ),
    ]
